export const cities = [
  "Gaillimh/Galway",
  "Lios Dúin Bhearna/Lisdoonvarna",
  "Ballydehob",
  "Baltimore",
  "Corcaigh/Cork",
  "City Centre",
  "Cill Chainnigh/Kilkenny",
  "Blackrock",
  "Baile Mhic Andáin/Thomastown",
  "Aird Mhór/Ardmore",
  "Waternish",
  "Dalry",
  "Belfast",
  "Peat Inn",
  "Leith",
  "Edinburgh",
  "Anstruther",
  "Grasmere",
  "Bowness-on-Windermere",
  "Cartmel",
  "Newcastle upon Tyne",
  "Menai Bridge/Porthaethwy",
  "Langho",
  "Pateley Bridge",
  "Birkenhead",
  "Fence",
  "Llandrillo",
  "Machynlleth",
  "Oldstead",
  "Chester",
  "Harome",
  "Leeds",
  "Montgomery/Trefaldwyn",
  "South Dalton",
  "Baslow",
  "Winteringham",
  "Ilfracombe",
  "Llanddewi Skirrid",
  "Padstow",
  "Birmingham",
  "Port Isaac",
  "Hampton in Arden",
  "Mountsorrel",
  "Whitebrook",
  "Penarth",
  "Portscatho",
  "Kenilworth",
  "Knowstone",
  "Stratford-upon-Avon",
  "Cheltenham",
  "Chagford",
  "Upper Hambleton",
  "Bristol",
  "Chew Magna",
  "Malmesbury",
  "Castle Combe",
  "Colerne",
  "Bath",
  "Lympstone",
  "Hunstanton",
  "Torquay",
  "Oxford",
  "Murcott",
  "Morston",
  "East Chisenbury",
  "Newbury",
  "Marlow",
  "Burchett's Green",
  "Shinfield",
  "Bray",
  "Winchester",
  "Bagshot",
  "Ascot",
  "Egham",
  "Kew",
  "Chiswick",
  "Little Dunmow",
  "Hammersmith",
  "Kensington",
  "Marylebone",
  "Regent's Park",
  "Fulham",
  "Bloomsbury",
  "Mayfair",
  "Soho",
  "Belgravia",
  "Ripley",
  "Westminster",
  "Chelsea",
  "Saint James's",
  "Victoria",
  "Clerkenwell",
  "London",
  "Shoreditch",
  "Finsbury",
  "Spitalfields",
  "City of London",
  "Bermondsey",
  "Clapham Common",
  "Wandsworth",
  "Dorking",
  "Horsham",
  "Gravetye",
  "Seasalter",
  "Biddenden",
  "Fordwich",
  "Saint Helier/Saint-Hélier",
  "Auchterarder",
  "Summerhouse",
  "Aughton",
  "Nottingham",
  "Great Milton",
  "Cambridge",
  "North Kensington",
  "Hyde Park",
];
