export const cuisines = [
  "Creative",
  "Classic cuisine",
  "Modern cuisine",
  "Japanese",
  "Modern British",
  "Creative British",
  "French",
  "Seafood",
  "Classic French",
  "Spanish",
  "Asian influences",
  "Traditional British",
  "Regional cuisine",
  "Italian",
  "Indian",
  "Mediterranean cuisine",
  "Chinese",
  "Creative French",
  "Scandinavian",
  "Modern French",
];
